- lib/u3d/installer.rb
- lib/u3d/unity_runner.rb
> Revert "Fix Linux runner and installation"

- lib/u3d/installer.rb
- lib/u3d/unity_runner.rb
> Revert "Make Linux runner functional again"

- lib/u3d/installer.rb
- lib/u3d/unity_runner.rb
> Revert "u3d/run: ensure parent dir to logfile exists before creating the file"

- lib/u3d/downloader.rb
> u3d/install: reduce cpu caused by lack of buffering and high console output #36

- lib/u3d/installer.rb
> Linux auto sanitize after install

- lib/u3d/commands.rb
- lib/u3d/commands_generator.rb
This allows to do things like
````
git pull && u3d install
````
> u3d/install local_install: if no version specified, fallback on version required by current project

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Rakefile
- lib/u3d/commands.rb
- lib/u3d/iniparser.rb
- lib/u3d/installer.rb
- lib/u3d_core/globals.rb
- lib/u3d_core/helper.rb
- spec/u3d/log_analyzer_spec.rb
- spec/u3d/unity_project_spec.rb
- spec/u3d/utils_spec.rb
- u3d.gemspec
@niezbop can you confirm this works on your machine before I merge? Thanks!
> Rubocop update version and fix windows compatibility

- lib/u3d/commands.rb
- spec/support/installations.rb
- spec/support/setups.rb
- spec/u3d/commands_spec.rb
Creating the WIP PR to trigger builds and follow up here.
> u3d/commands: add unit tests and fix 2 small install command issues

- lib/u3d/downloader.rb
> Disable trick to reduce CPU on slow network as it slows down download on fast networks

- config/log_rules.json
> Add log rules to parse exceptions and aborts

- lib/u3d/unity_versions.rb
Linux version fetcher forum page changed
> u3d/available: restore Linux version.

- lib/u3d/commands.rb
- lib/u3d/commands_generator.rb
> u3d/credentials fix ArgumentError in commands (fixes #148)

- lib/u3d/commands.rb
> Fix module name issue for Globals call

- lib/u3d/installation.rb
> Fix Windows version detection for Unity4 (fixes #165)

- lib/u3d/installer.rb
- spec/support/installations.rb
- spec/u3d/installer_spec.rb
Also remove unused sorting in *Installer.installed
> u3d/list: also detect previously installed deb packages on Linux (fixes #189)

- lib/u3d/cache.rb
- lib/u3d/iniparser.rb
- lib/u3d/unity_version_definition.rb
- lib/u3d/unity_versions.rb
- lib/u3d/utils.rb
- spec/support/download_archives.rb
- spec/u3d/iniparser_spec.rb
- spec/u3d/unity_versions_spec.rb
This fixes #243 and should get us closer to support #242.
> u3d/available: fix forums parsing and move ini faking/downloading at available time, to support package based Linux versions

- lib/u3d/downloader.rb
- lib/u3d/installation.rb
- lib/u3d/installer.rb
> u3d/install linux xz format (fixes #251)

- README.md
> Document locale unicode requirements (fixes #268)

- README.md
- WIP
- lib/u3d/commands.rb
- lib/u3d/commands_generator.rb
- lib/u3d/installer.rb
- lib/u3d/utils.rb
- lib/u3d_core/admin_tools.rb
- lib/u3d_core/helper.rb
- spec/u3d/installer_spec.rb
Fixes #274 
I am splitting this PR in various pieces. This PR is based on top:
[MERGED]  #290 #291 #292 #293 #294 
#295 #296
> u3d/move command, renaming install dirs. Support long version names. Fixes #274

- lib/u3d_core/command_executor.rb
- spec/u3d_core/command_executor_spec.rb
> u3d/* automatically retry admin privilege elevation #236

- lib/u3d/iniparser.rb
- lib/u3d/installer.rb
- lib/u3d_core/admin_tools.rb
- spec/u3d/iniparser_spec.rb
- spec/u3d/installer_spec.rb
> u3d/install: support full pkg for Linux

- lib/u3d/installer.rb
> Tentative fix for #302

- lib/u3d/commands.rb
- lib/u3d/commands_generator.rb
- lib/u3d/unity_runner.rb
- spec/u3d/commands_spec.rb
> u3d/runner: Fix -projectPath argument

- Gemfile.lock
- u3d.gemspec
> Lower dependency on rubyzip to 1.3.0 for fastlane compatibility

- .circleci/config.yml
- Gemfile.lock
- lib/u3d/commands_generator.rb
- lib/u3d_core/env.rb
- lib/u3d_core/helper.rb
- lib/u3d_core/update_checker/changelog.rb
- lib/u3d_core/update_checker/update_checker.rb
- u3d.gemspec
Support displaying u3d updates
a-la-fastlane
We'll wait for #389 to be fixed to roll this out.
> Support displaying u3d updates

- .github_changelog_generator
- CHANGELOG.md
- Gemfile.lock
[DESCRIBE YOUR PULL REQUEST HERE]
> Release 1.3.0

- lib/u3d/hub_modules_parser.rb
- lib/u3d/ini_modules_parser.rb
- lib/u3d/utils.rb
Rubocop autofix introduced a bug.
> [Fix] Broken install command, fixes #421
