DragonBox/u3d

lib/u3d/unity_version_number.rb
lib/u3d/unity_versions.rb
lib/u3d/utils.rb

The LOG_RULES.md had some typos left, and some inconsistencies that needed tackling.
The installer.rb undergoes two modifications:
* The Runner class, used to run Unity, has been moved to a separate file to further increase clarity.
* Installer was asking to sanitize at each package installation when several were installed at once. Minor changes have been made so that the sanitation is offered only once. NOTE: the installation methods are now instance methods and no longer class methods.
Small fix regarding Linux versions, versions above 5.5.0 should now be listed as well.

Linux versions fix

---

lib/u3d/unity_runner.rb

**Issue**
Sometimes u3d failed to catch the beginning of the logs, and therefore missed releveant pieces of information.
**Reason**
The tailing is done on a separated thread than the one launching Unity. Both of the threads can have different time to setup and start behaving as intended, and it could happen that the tailing wasn't completly setup when Unity started logging, resulting in the loss of the very first few logs.
**Fix**
Quite simply, wait for the tail thread to be completly setup, then start Unity. The tailing thread will now properly parse the first logs!

Fix tail logs synchronization

---

lib/u3d/log_analyzer.rb

**Issue**
U3d stops logging when using the prettyfier and a rule failed to capture something in the logs and tried to access it.
**Fix**
Failure has been rescued and logged, so the user knows something went wrong, but it continues to log so that it doesn't interrupt the user workflow.

Fix missing key failure

---

examples/Example2/fastlane/Fastfile
lib/u3d/unity_runner.rb

Using -logFile /dev/stdout crashes u3d right now. This PR makes it functional. The prettifyer isn't yet plugged into it, but the output is now displayed.

Better support for /dev/stdout (#11)

---

lib/u3d/installer.rb
lib/u3d_core/command_executor.rb

there are 4 at least problems right now.
3 under install
* one small typo in variable name (fixed)
* one where command executor doesn't like when 2 commands are passed (cd /dir; something)
* one where mkdir fails because of lack of privileges. We could detect if we need sudo to create repo by doing `touch -d /opt/` and test for result
Really not sure why so many issues. It looks like this was implemented in an environment where root was already there
and then even if I manage to install, `u3d list` doesn't work as expected
````
$ u3d list
error: Couldn't find file /opt/Unity_2017.2.0b2/Data/PlaybackEngines/LinuxStandaloneSupport/ivy.xml. Use --trace to view backtrace
````
it should be searching under `/opt/Unity_2017.2.0b2/unity-editor-2017.2.0b2/Editor/Data/PlaybackEngines/LinuxStandalone …

Make Linux installer functional again

---

lib/u3d/installer.rb

The installation sanitizer detects if an installation needs to be sanitized based on platform specific logic. Theses changes have been motivated by the issues under Linux, which this commit addresses as well.

Change sanitizer to be platform specific

---

lib/u3d/installer.rb
lib/u3d/unity_runner.rb

* Runner now makes sure that the directory containing the log exists
before attempting to create it.
* The UnityProject now parses correctly its version under Linux
* LinuxInstallation uses the correct path for the exe

Fix Linux runner and installation

---

lib/u3d/installer.rb
lib/u3d/unity_runner.rb
spec/u3d/unity_project_spec.rb

The YAML configuration file of a Unity project may often refer to weird Linux versions such as '2017.1.0xf3Linux'. To be sure that this is recognized by u3d, we parse this type of version (so in this example it would be '2017.1.0f3').
Comes with spec to make sure it works as intended.

[linux] Adjust to weird editor versions stored under ProjectSettings/ProjectVersion.txt

---

lib/u3d/commands.rb

Do not reinstall Unity or its packages if already present. Also prevent duplication because of sanitization.

---

lib/u3d/commands.rb

Fomats the versions listed by `u3d list` so that they are aligned nicely.

u3d list: properly align versions and paths in output

---

.rubocop.yml
Rakefile
examples/Example1/Gemfile
examples/Example2/Gemfile
lib/u3d/commands.rb
lib/u3d/commands_generator.rb
lib/u3d/downloader.rb
lib/u3d/installer.rb
lib/u3d/log_analyzer.rb
lib/u3d/unity_runner.rb
lib/u3d/unity_versions.rb
lib/u3d_core/command_executor.rb
lib/u3d_core/command_runner.rb
lib/u3d_core/credentials.rb
lib/u3d_core/globals.rb
lib/u3d_core/helper.rb
lib/u3d_core/ui/implementations/shell.rb
spec/spec_helper.rb
spec/u3d/iniparser_spec.rb
spec/u3d/log_analyzer_spec.rb

Rubocop cleanups

---

lib/u3d/commands.rb

Rubocop formatting broke the downloader and local installer with wrong number of arguments.

[FIX] Download and local installer fix

---

lib/u3d/commands.rb

u3d was going pretty far in the download process before realizing the version was not in the cache, and returning. It returns now way earlier.

u3d/install: do not try to download unknown versions (i.e. not in cache)

---

lib/u3d/downloader.rb
lib/u3d/iniparser.rb
lib/u3d/unity_versions.rb
spec/u3d/iniparser_spec.rb

See #21 for the issue.
Fixes the issue by checking if the size of the file that is present is correct. Unlike under Windows or Mac, where the size is checkable in the .ini files, Linux doesn't uses ini files and therefore must rely on checking the expected size of the file online. As this can lead to a failure for some reason, if the file size cannot be verified, then the file is assumed correct.

Fix corrupted file on Linux

---

spec/support/download_archives.rb
spec/u3d/unity_versions_spec.rb

Refactors all the rspec tests related to UnityVersions as unit tests and no longer integration tests.
Adds test for nested versions in Linux as well.
Addresses #2

Make unity versions test unit

---

lib/u3d/installation.rb

Do not crash when no PlaybackEngines are found. Fixes #69

Do not crash when no PlaybackEngines are found

---

spec/u3d/commands_spec.rb

Changes all uses of 'describe' keyword to 'context' keyword when
describing a context rather than specifying the tested method.
This is not a functionnal change, 'context' is an alias for 'describe'.
So is 'xcontext' for 'xdescribe'.

Make commands_spec more readable

---

lib/u3d/unity_runner.rb

Method `find_logFile_in_args` was moved to class method but this call was still using instance method.

Runner fix

---

lib/u3d/installer.rb

This fix makes sure that we move new Unity installs under our correct format (ie Unity_0.0.0x0) for fresh installs.
This should fix #68, and this being fixed would fix #71

Mac Installer fix

---

lib/u3d_core/ui/implementations/shell.rb
spec/spec_helper.rb
spec/u3d_core/ui/implementations/shell_spec.rb

logger: Hide EPIPE errors when stdout already closed

---

config/log_rules.json

The order of the logs has changed from Unity5+ to Unity2017+ and the INIT
log phase was not starting as intended. This adds an alternative
entrypoint for the phase to match 2017 ordering.
Fixes #99

Fix INIT log phase not starting when intended

---

lib/u3d/downloader.rb
lib/u3d/installer.rb
spec/u3d/downloader_spec.rb
spec/u3d/installer_spec.rb

Note that I've moved to use shellescape in Linux installer. We should quickly test it.

u3d/install: move chmod +x of linux files at install time (Fixes #91)

---

config/log_rules.json

Fixes #123 
Adds a generic rule to catch error messages when there is an issue while loading dependencies on Linux.

u3d/prettify: add rule to catch library loading errors

---

config/log_rules.json
lib/u3d/log_analyzer.rb

- Modifies some of the compiler rules to match the behaviour of the newer
versions of Unity3d.
- Makes sure that the compiler phase finishes to avoid duplicated
messages.

u3d/prettify: modify compiler rule parsing for 2017+

---

README.md
lib/u3d/commands.rb
lib/u3d/commands_generator.rb
lib/u3d/installer.rb

Before installing Unity on Linux, the installer will now install its required dependencies.

u3d/dependencies: add command to install Linux dependencies

---

lib/u3d/unity_runner.rb
lib/u3d_core/command_executor.rb

Testing using `examples/Example1`
```
bundle exec u3d -r -- -logFile /dev/stdout -executeMethod U3d.EditorRun.LoadSaveScenes -quit -batchmode
bundle exec u3d  -- -logFile /dev/stdout -executeMethod U3d.EditorRun.LoadSaveScenes -quit -batchmode
bundle exec u3d -r -- -logFile /tmp/stdout -executeMethod U3d.EditorRun.LoadSaveScenes -quit -batchmode
bundle exec u3d  -- -logFile /tmp/stdout -executeMethod U3d.EditorRun.LoadSaveScenes -quit -batchmode
```
all works on mac
I had to make sure the `\n` is passed to the output_callback by command_executor for it to work.
```
bundle exec u3d -r -- -logFile /dev/stdout -executeMethod U3d.EditorRun.LoadSaveScenes -quit -batchmode -nographics
bundle exec u3d  -- -logFile /dev/stdout -executeMethod U3d.EditorRun.LoadSaveScenes -quit -batchmode …
```

u3d/prettify: also plug log analyzer on stdout (Fixes #18 #43)

---

lib/u3d/log_analyzer.rb

Current implementation was doing:

u3d/analyzer: remove extra end of lines in context information

---

lib/u3d/installer.rb

u3d/installer: allow to find the installation we just installed, and fallback on spotlight on mac

---

lib/u3d/installation.rb

The idea of this was to see if the module name stored under ivy.xml was the same as under the .ini. To solve #161. It's closer, but not 100% matching.

u3d/list find package names under PlaybackEngines ivy.xml

---

config/log_rules.json
lib/u3d/log_analyzer.rb

* Some log rules could not be ended in projects with strange characters in the path to the file logging.
* Also fixes the fact that u3d tried to finish the active phase even though there was none.

Fix log termination

---

lib/u3d/utils.rb

Always use the server declared size first, and force printing when done.
This should solve inaccurate Windows package sizes and fix #164

u3d/downloader: print progress improvements (fix #164)

---

fastlane-plugin-u3d/lib/fastlane/plugin/u3d/actions/u3d_action.rb

Calls to the plugin are failing when the option is specified because the type is not correct.

Fix unity_version argument of fastlane plugin u3d type

---

lib/u3d/commands.rb
lib/u3d/installation.rb
spec/support/installations.rb

Fixes #198 
This solve the issues of non-matching package name between installed and available by:
- Mapping the names of the installed package and the available package
- Detecting some folders on the local install for "special package" (Documentation, Standard Assets...)

u3d/install: do not reinstall already installed packages

---

config/log_rules.json
spec/u3d/log_analyzer_spec.rb

This adds rules to the prettifier so that all the license-related informations appear in the logs.

u3d/prettify: update ruleset with LICENSE SYSTEM rules

---

config/log_rules.json
spec/u3d/log_analyzer_spec.rb

This removes all jenkins-specific rules as they do not belong in u3d.

u3d/prettify: remove Jenkins rules

---

lib/u3d/cache.rb
lib/u3d/commands.rb
spec/u3d/commands_spec.rb

* enable to access cache pass from a class method
* hide a method private
* reuse cache_versions in commands.available as to have a single place where we instantiate the Cache class

u3d/internals: a serie of cache related refactors

---

lib/u3d/commands_generator.rb
lib/u3d/downloader.rb
spec/spec_helper.rb
spec/u3d/downloader_spec.rb

This adds a new option to `u3d install` so that the user can specify the target of its destination.
`u3d install <SOME STUFF> --download_path <SOME PATH>` will download if not already present at specified path and install it from this file.
`u3d install <SOME STUFF> --no-install --download_path <SOME PATH>` will download packages at some location, and make sure that they don't already exist there.
This works for both absolute and relative paths.

u3d/install: allow to specify packages download directory using an environment variable

---

lib/u3d/commands.rb
lib/u3d/commands_generator.rb
lib/u3d_core/core_ext/hash.rb
spec/u3d/commands_spec.rb

requires #215 to be merged. I will rebase when ready.

u3d/available: allow to match using regular expression

---

lib/u3d/cache.rb
lib/u3d/commands.rb
lib/u3d_core/core_ext/operating_system_symbol.rb
spec/u3d/commands_spec.rb

This is meant to fix #142.
Note that I haven't yet tested how this impacts the Linux version, as the Linux version normally creates the fake ini file as part of the discovering procedure
This depends on #215 and #216 and will need a rebase.

u3d/available: introduce a central cache (fixes #142)

---

lib/u3d/commands.rb
spec/u3d/commands_spec.rb

This make it so that `-u` supports regular expression such as `2017\.*`,  `5\..\.0.+`...

u3d/available: more regex support

---

lib/u3d/commands.rb
lib/u3d/commands_generator.rb
lib/u3d/download_validator.rb
lib/u3d/downloader.rb
lib/u3d/utils.rb
spec/u3d/downloader_spec.rb

Statuses:
* downloader appears to work for both Windows and Mac (builds on #226)
* install works on Mac, so no regression here.
* EULA is not dealt with
* installation on Windows should probably reuse the new cmd information in the .ini file
* tests missing...

u3d/install Unity 2018. Download works on Windows and Mac and Mac installs. Fixes #225

---

lib/u3d/installer.rb

This improves the output of the installer by making it more obvious what is happening, and make it similar to the downloader output.

u3d/install: improve messages

---

lib/u3d/downloader.rb
lib/u3d/installer.rb
lib/u3d/utils.rb

This adds support for downloading and installing .msi packages for Windows.

u3d/install: add support for installing .msi packages on Windows

---

config/log_rules.json

This fixes a prettifier bug where it failed to detect the end of some specific log rules, resulting in a number of `[INIT] Could not finish active rule 'log_warning'. Aborting it. Context:`. This was due to the presence of `.` in some file names that was not properly parsed.
This also takes care of the other special characters common in file names.

u3d/prettify: Fix rule termination when there are special characters in the file name

---

README.md
fastlane-plugin-u3d/README.md
fastlane-plugin-u3d/fastlane-plugin-u3d.gemspec
fastlane-plugin-u3d/lib/fastlane/plugin/u3d/actions/u3d_action.rb
lib/u3d/commands_generator.rb
lib/u3d/installer.rb
lib/u3d/version.rb

This standardizes the various output of u3d. Unity is at times referenced as Unity3d or Unity3D. The commands are also quite chaotic, and very different in the way they were described. This pull request aims to bring a bit more harmony in the various outputs of u3d so that the tool is less confusing and easier to use.

u3d: standardize log and descriptions

---

lib/u3d/cache.rb
lib/u3d/iniparser.rb
lib/u3d_core/helper.rb

Move the duplicated data_path into a helper method so that it is only defined once, and can be used elsewhere.

Move duplicated data_path out of U3d::Cache/U3d::INIparser to U3dCore::Helper

---

config/log_rules.json

Fixes #269 
This simply makes it so that the prettifier rules for logging (normal, assertion, warning and error) match format logs as well so that they appear in the prettifier output (and consequently in the `u3d run` output as well). I have extended the pattern for matching a logging rule so that `Debug.LogXXXFormat` is treated the same way as `Debug.LogXXX`, making it easier to read logs.

u3d/prettify: Fix UnityEngine.Debug.LogXXXFormat not being caught

---

config/log_rules.json

The u3d prettifier currently fails to catch most enlighten messages. While these are not the most important messages, failure must be caught as they cause builds to fail. This PR addresses that issue.

u3d/prettify: Catch Enlighten jobs failure

---

config/log_rules.json

The prettifier was considering that lines such as the following
```
This is a warning because of an exception (Exception: message)
```
should start the exception rule, while it should not. This makes it so
that the rule makes sure that there is no parenthesis on the line before
the exception to start the exception rule.

u3d/prettify: fix exception rule start pattern

---

lib/u3d/unity_versions.rb

u3d/available support LTS (#276)

---

config/log_rules.json

Addresses #278 
The u3d prettifier failed to catch the messages displayed by the buildpipeline, thus missing on critical information. The messages are displayed as warnings, as most messages coming from the build pipeline are.

u3d/prettify: catch build pipeline messages

---

lib/u3d/commands.rb
lib/u3d/installation.rb
spec/support/installations.rb

Tested on Linux/Windows/Mac on the computers I had access to, would need slightly more testing to make sure Unity doesn't do weird things with special builds. So adding the feature as part of `list` to test it a bit more.
We need to work a bit more on the overall feature set to see how to solve #274
Mac:
Linux:
Windows:
Meh... believe me it worked.

u3d/list: display full revision number (prepares for #274)

---

README.md
lib/u3d/commands.rb
lib/u3d/installer.rb
spec/support/setups.rb
spec/u3d/commands_spec.rb
spec/u3d/installer_spec.rb

This is a breaking functional change, but I don't think we ever advertised it. I consider the fact that we were sanitizing outside of list a bug and not something to be depended upon.

u3d/sanitize: sanitize on list only + cleanups and refactors

---

lib/u3d_core/command_executor.rb

Consequence was that in case of invalid password, it was keeping the invalid password in memory and reusing it indefinitely.

u3d/internals: grant_admin wasn't using has_admin_privileges? to get the privileges on non windows platforms

---

lib/u3d/unity_versions.rb

Fixes #321 
Unity has introduced a new pattern for downloading the Editor in the 2018.2 release, which broke our integration.
It went from `https://download.unity3d.com/download_unity/4cb482063d12/MacEditorInstaller/Unity-2018.1.7f1.pkg` [2018.1.7f1] to `https://download.unity3d.com/download_unity/787658998520/UnityDownloadAssistant-2018.2.0f2.dmg` [2018.2.0f2]. While this also means that the installer has apparently changed, they still use the old route pattern to download the editor (meaning that `https://download.unity3d.com/download_unity/787658998520/MacEditorInstaller/Unity-2018.2.0f2.pkg` is still a valid route), so this should not be an issue.

u3d/versions: Accept new pattern for mac above 2018.2+

---

README.md
lib/u3d/commands.rb
lib/u3d/commands_generator.rb

This is a small change that makes it possible to still retrieve the latest unity versions when the central cache doesn't know them. It adds an option to `u3d available`.

u3d/available: Add option to not use the central cache

---

lib/u3d/installation.rb
lib/u3d/unity_versions.rb
spec/support/download_archives.rb
spec/u3d/unity_versions_spec.rb

Fixes #337, making 2018.3.0f2 available on Linux. It does this by also searching the forum pages directly for `LINUX_DOWNLOAD`. It also allows the download link to be encompassed in single or double quotes.
I've tested on my Mac that `u3d available -o linux` responds with the latest version and extended the rspecs to cover this case. I have not yet tested on a linux system that the download and install completes successfully. I will do this when I next have access to a linux system - should be able to on Monday.

u3d/available: Make Linux 2018.3.0f2 available on linux #337

---

lib/u3d/unity_versions.rb
spec/support/download_archives.rb
spec/u3d/unity_versions_spec.rb

Unity has recently updated their listing of the latest releases for betas notably.
This restore the functionnality by fetching the latest information.
Fixes #330

u3d/unity_versions: fix missing latest versions

---

lib/u3d/installer.rb

Fixes #310 by adding `-t*` to the 7z `command`. Thanks to @jsmouret-vl for posting the fix in the issue. Tested and working on linux to install Android support, where it was broken for me, prompting the PR.

Add `-t*` flag for 7z when unpacking packages

---

lib/u3d/commands.rb
spec/u3d/commands_spec.rb

[DESCRIBE YOUR PULL REQUEST HERE]

u3d/install exit 1 when version not found. Fixes #343

---

lib/u3d.rb
lib/u3d/asset.rb
lib/u3d/unity_project.rb
spec/u3d/asset_spec.rb

This is some work I have done recently to look for asset usage in a Unity project, and I believe it belongs in u3d. It enables one to easily browse the asset in his project and find how they reference one another, either by guid or by name.
Sample command possible:
```
$ u3d console
Welcome to u3d interactive!
>> U3d::Asset.glob('Assets/Some/Path/*').map {|asset| asset.users}.flatten.uniq
[...]
```
Which is quite useful in my opinion and makes for a powerful debugging tool.

u3d/asset: add feature that enables easy inspection of asset in a Unity project

---

lib/u3d/unity_versions.rb
spec/support/download_archives.rb
spec/u3d/unity_versions_spec.rb

More stable and finds both older and newer versions that are dependent on the DownloadAssistant

list/available: find Mac or Windows version based on the unity_shader package. Fixes #349

---

lib/u3d/iniparser.rb
spec/u3d/iniparser_spec.rb

Prevent empty ini files from being created and ignore them (fixes #356)

---

lib/u3d/unity_versions.rb
spec/support/download_archives.rb
spec/u3d/unity_versions_spec.rb

Fixes #360  by using the same mechanism of fetching Unity's json manifest to retrieve missing Unity versions.
Tested with `u3d available -f --no-central -o linux`
Result:
```
paulniezborala@Pauls-MBP u3d (master) $ git diff --no-index current.versions newer.versions
diff --git a/current.versions b/newer.versions
index 0950a87..1a001e6 100644
--- a/current.versions
+++ b/newer.versions
@@ -2,7 +2,7 @@
Loading Unity releases
Loading Unity latest releases
Found 7 latest releases.
-Found 84 releases.
+Found 91 releases.
Version 5.1.0f3: http://download.unity3d.com/download_unity/unity-editor-installer-5.1.0f3+2015091501.sh
Version 5.2.2f1: http://files.unity3d.com/levi/unity-editor-installer-5.2.2f1+20151018.sh
Version 5.3.0f4: http://download.unity3d.com/download_unity/linux/unity-editor-inst …
```

Use the VersionsFetcher with Unity's json on Linux as well

---

lib/u3d/installation.rb

Starting from 2019.2.x, Unity does not use `ivy.xml` anymore. This means that our version retrieval does not work any longer.
This addresses this issue by using the same system we use to retrieve the build number from the .exe, which should prove to be more robust in the long run.
Fixes #354 
Fixes #367

u3d/installation: fix the version retrieving for Windows on Unity 2019.2.x and onwards

---

README.md
lib/u3d/installer.rb
spec/support/installations.rb
spec/u3d/installer_spec.rb

`u3d install` supports custom installation paths, but does not list them correctly in the rest of the application.
This means that `u3d run`, package installs and such commands will not detect properly the version installed in a custom path.
This fixes this behaviour by adding an environment variable `U3D_EXTRA_PATHS` which is a list of additional paths to look for installed Unity versions.
Fixes #370 
Fixes #371

u3d/installer: support custom install paths through U3D_EXTRA_PATHS

---

lib/u3d/commands.rb
spec/u3d/commands_spec.rb

u3d/install: verify package names before we ensure setup coherence (fixes #385) (regression from 1.2.0)

---

lib/u3d/installer.rb
spec/u3d/installer_spec.rb
spec/u3d_core/helper_spec.rb

The documentation states that U3D_EXTRA_PATHS are windows style.
Fixes #383

u3d/install: convert Windows paths to ruby paths when treating U3D_EXTRA_PATHS

---

DEVELOPMENT_PROCESS.md
Rakefile

I used it to create the releases: https://github.com/DragonBox/u3d/releases
Note that I could make it even better by properly  using it in the rake release task, but didn't care right now.

Create Github releases. Required for #390. [Fixes #389]

---

lib/u3d.rb
lib/u3d/commands.rb
lib/u3d/downloader.rb
lib/u3d/ini_modules_parser.rb
lib/u3d/installation.rb
lib/u3d/installer.rb

Definitively WIP with Windows not supported at all.
The approach is to use the `modules.asset` files to detect Playback Engines. @niezbop any better idea on how to support this?
I will also need some help to test this on Windows at some point. Maybe @BastianBlokland would like to test it on Linux?

Detect 2019 modules and allow to install 2019, skipping dmg install for now

---

.circleci/config.yml
.gitignore
Gemfile.lock
lib/u3d/hub_modules_parser.rb

We know that non-latest releases don't have their optional modules available. This is an attempt to fix it.
Looks like it works.
```
$ bundle console
U3d::Commands.list_available(options: {unity_version: '2020.3.10f1', packages: 1})
Version 2020.3.10f1: https://download.unity3d.com/download_unity/297d780c91bc/
Packages:
- Unity
- Mono
- Visualstudio
- Android
- Ios
- Appletv
- Linux-il2cpp
- Linux-mono
- Mac-il2cpp
- Webgl
- Windows-mono
- Lumin
- Documentation
- Language-ja
- Language-ko
- Language-zh-hans
- Language-zh-hant
- Android-sdk-ndk-tools
- Android-sdk-platform-tools
- Android-sdk-build-tools
- Android-sdk-platforms
- Android-ndk
- Android-open-jdk
=> ["2020.3.10f1"] 
U3d::Commands.install(args: ["2020.3.26f1"], options:{download: true, all: true, install:true}) …
```

Fix installation of modules for non latest releases

---

lib/u3d/installation.rb

[DESCRIBE YOUR PULL REQUEST HERE]
This pull request solves the error when installing in Linux a Unity version 2020. It seems that untill Unity 2019, the unity_builtin_extra file has the string version coded at byte position 20. In 2020 the string version is coded from byte position 48. It has been coded a check for trying reading what it is expected in 2019 and if it is "\x00" set the seek position for 2020.

Fixing error when installing Unity 2020 version in Linux

---

Rakefile

rspec fails if you have conflicting versions of coveralls and simplecov
```
acostej@MacBook-Pro ~/Code/OSS/u3d (master) rspec
An error occurred while loading spec_helper. - Did you mean?
rspec ./spec/spec_helper.rb
Failure/Error: require 'coveralls'
Gem::ConflictError:
Unable to activate coveralls-0.8.23, because simplecov-0.17.1 conflicts with simplecov (~> 0.16.1)
No examples found.
No examples found.
Finished in 0.00002 seconds (files took 0.18473 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
Finished in 0.00002 seconds (files took 0.18473 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Run rspec within bundle exec

---

lib/u3d/hub_modules_parser.rb

#416 seems to have introduced a bug where an attempt is made to call a method named `info` on the UI interface, but this method doesn't exist. This PR simply changes the call to `UI.message` instead.
Fixes #430

fix: replace usage of nonexistent UI.info method

---

lib/u3d/unity_versions.rb

fix: don't attempt to append to frozen string

---

lib/u3d/utils.rb

…
Fixes #433 
Unity has started blocking the default Ruby agent, which leads u3d to face 403 Forbidden when making requests to their system. This makes it so that our ongoing requests use Mozilla's browser agent to bypass this issue.

[Fix] U3d::Utils: replace Ruby agent with another one to bypass 403 from Unity

---

Gemfile.lock
examples/Example1/Gemfile.lock
examples/Example2/Gemfile.lock
u3d.gemspec

This PR updates the version numbers in the gemspec to resolve a circular dependency problem that prevented upgrading Fastlane (to version 2.220.0). Specifically, updated security from 0.1.3 to 0.1.5 to align with Fastlane's newer version requirements.
This change has been tested and ensures that Fastlane can now be successfully upgraded without conflicts.
Contributed on behalf of [Agens](https://agens.no).

Update package dependencies to resolve circular dependency issue

---

.circleci/config.yml
Gemfile.lock

circle fails, making some changes to make it pass again.

Bump nio4r to pass installation on some CI platforms
